In [7]:
#cvs파일 입출력

import csv

#csv파일 작성
with open("./day03/student.csv","w",newline="") as f :
    #write 작성객체 생성
    write=csv.writer(f)
    write.writerow(["학번","이름","나이"]) #write라는 쓰기객체를 생성하고 그걸 이용해서 csv메소드인 writeow를 통해 내용작성
    write.writerow([1,"둘리",10])
    write.writerow([2,"도우너",11])

print("파일생성완료!")

파일생성완료!


In [12]:
#<csv파일 작성하기 실습>

# import csv #이미 불러왔으니까 주석처리

with open("./day03/band.csv","w") as f:
    band_namew=csv.writer(f)
    band_namew.writerow(["밴드명","멤버수","대표멤버"])#wirterow는 리스트로 1행씩 넣는 형태
    band_namew.writerow(["유다빈밴드",4,"유다빈"])

print("band.csv파일 생성완료!")

band.csv파일 생성완료!


In [20]:
#csv파일 읽어오기

with open("./day03/student.csv","r") as f:
    reader=csv.reader(f) #이렇게만쓰면 해당 파일의 주소만 나옴.
#파일을 작성할때 리스트로 작성을 했기때문에 파일을 읽어오기위해서는 리스트로 형변환시켜주어야함
    reader=list(reader)

print(reader) #아까 작성했었던 파일의 내용이 불러와짐

[['학번', '이름', '나이'], ['1', '둘리', '10'], ['2', '도우너', '11']]


In [35]:
#csv파일 불러오기 실습

with open("./day03/band.csv","r") as f:
    band_r=csv.reader(f)
    band_r=list(band_r)

print(band_r)

[['밴드명', '멤버수', '대표멤버'], [], ['유다빈밴드', '4', '유다빈'], []]


In [37]:
#csv 여러행 작성하기

import csv

with open("./day03/studenct.csv","w") as f:
    write=csv.writer(f)
    write.writerows([["학번","이름","나이"],[20190951,"전신영",25],[20190952,"유다빈",26]])

print("파일생성!")

파일생성!


In [109]:
#csv파일을 딕셔너리형태로 쓰고 읽어오기
#csv.DictWriter

cate=["히어로명","이름","직업"]
data = [{"히어로명" : "스파이더맨", "이름":"피터 파커", "직업":"고등학생"},
       {"히어로명" : "아이언맨", "이름" : "토니 스타크", "직업" : "발명가"},
       {"히어로명" : "캡틴 아메리카", "이름" : "스티븐 로저스", "직업" :"군인"}]


with open("./day03/marvel.csv","w",newline="") as f:
    w = csv.DictWriter(f,fieldnames=cate)
    #fieldnames를 이용해서 파일 객체의 열제목 설정
    w.writeheader() #첫번째 행에 항목이름을 넣을것인지 설정
    w.writherows(data)
    
print('파일생성!')

SyntaxError: invalid syntax (2824405532.py, line 16)

In [145]:
#openpyxl 

#파일열기
import openpyxl

#통합문서(Workbook)객체 생성

#객체명=Workbook의 클래스를 생성해준것
wb=openpyxl.Workbook()

#워크시트의 객체 생성
ws=wb.active #첫번째 시트를 활성화 시키는것이 기본값
print(ws)

#워크시트 생성 : Workbook_create_sheet()

#통합문서 객체명.시트만드는 메소드(시트이름)
wb.create_sheet("new01")

#워크시트 목록 확인
print(wb.sheetnames,type(wb.sheetnames)) #통합문서 객체명.sheetnames사용하면 시트들의 이름을 볼 수 있음
#'Sheet', 'new01' sheet(ws=wb.active할떄 첫번째 시트를 활성화시키는것이 기본값이기때문에 첫번째 시트로 생성된것)

#워크시트 생성위치 지정
wb.create_sheet("new sheet01") #위치설정을 하지 않으면 맨 끝에 추가
wb.create_sheet("new sheet02",0)#인덱스 위치 0번=첫번째
wb.create_sheet("new sheet03",-1) #인덱스-1을 입력했지만 위치값을 지정하지 않으면 맨 끝으로 간다는 기능이 이미 있기때문에
#-1을 입력하게 되면 맨끝에서 두번째 값으로 이동

print(wb.sheetnames)
print(ws) #워크시트의 객체명으로 지금 현재 통합문서(tset)에서 활성화되어있는 워크시트를 확인할 수 있음
ws.title="시트1수정"
print(ws) #현재 활성화 되어있는 시트의 이름이 수정된걸 확인할 수 있음
print(wb.sheetnames)

#다른시트 활성화
#워크시트 객체명을 활용
ws=wb["new sheet02"] #딕셔너리에서 키값으로 벨류값에 접근하는 방식과 비슷
print(ws) #활성화 되어있는 시트 확인아면 <Worksheet "new sheet02">
ws=wb["시트1수정"]
print(ws) #다시 활성화 되어있는 시트 이름 변경

#엑셀파일 저장
wb.save("./day03/test.xlsx") #시트를 파이썬에서 다 만들었다면 꼭 저장

<Worksheet "Sheet">
['Sheet', 'new01'] <class 'list'>
['new sheet02', 'Sheet', 'new01', 'new sheet03', 'new sheet01']
<Worksheet "Sheet">
<Worksheet "시트1수정">
['new sheet02', '시트1수정', 'new01', 'new sheet03', 'new sheet01']
<Worksheet "new sheet02">
<Worksheet "시트1수정">


In [199]:
#단일셀 접근

print(ws) #활성화된 객체 확인

ws["A1"]=10
print(ws["A1"]) #<Cell '시트1수정'.A1> 위치 출력
#그냥 출력하면 이렇게 위치만 출력이 되기때문에
print(ws["A1"].value) #값을 알려주는 .value를 사용하면 A1셀에 저장된 값을 확인할 수 있음
ws["C1"]="안녕!"
print(ws["C1"].value)

#worksheet cell()사용하기
b=ws.cell(row=1, column=2, value=20) # 1행 2열셀에 20저장
s=ws.cell(row=2 , column=2, value=30)


#다중 셀 접근 : 슬라이싱 이용
cell_range=ws["A1":"C2"]
print(ws["A1":"C2"]) #이렇게만 쓰면 위치정보 확인/ 이중튜플 형식으로 정보값확인 가능
print()
#for문을 이용해서 셀요소를 하나하나 가져와서 확인가능 = 튜플의 언패킹

for row in cell_range:
    for cell in row:
        print(cell.value) #셀 요소 하나하나 가져와줌. None은 값이 들어오지 않았기때문

print()
print(ws["C"]) #C열 전체값이선택이 된거긴하지만 C열의 전체값을 보여줄수가 없어서 우리가 활성화해준 C2까지만 나온것
print(ws["C":"D"])
print(ws[10]) #10행의 전체
print(ws[10:20])

#파일저장
wb.save("./day03/test.xlsx")
wb.close() #파일의 모든 작업이 끝났으면 close()로 파일을 닫아주어야함

<Worksheet "시트1수정">
<Cell '시트1수정'.A1>
10
안녕!
((<Cell '시트1수정'.A1>, <Cell '시트1수정'.B1>, <Cell '시트1수정'.C1>), (<Cell '시트1수정'.A2>, <Cell '시트1수정'.B2>, <Cell '시트1수정'.C2>))

10
20
안녕!
None
30
None

(<Cell '시트1수정'.C1>, <Cell '시트1수정'.C2>, <Cell '시트1수정'.C3>, <Cell '시트1수정'.C4>, <Cell '시트1수정'.C5>, <Cell '시트1수정'.C6>, <Cell '시트1수정'.C7>, <Cell '시트1수정'.C8>, <Cell '시트1수정'.C9>, <Cell '시트1수정'.C10>, <Cell '시트1수정'.C11>, <Cell '시트1수정'.C12>, <Cell '시트1수정'.C13>, <Cell '시트1수정'.C14>, <Cell '시트1수정'.C15>, <Cell '시트1수정'.C16>, <Cell '시트1수정'.C17>, <Cell '시트1수정'.C18>, <Cell '시트1수정'.C19>, <Cell '시트1수정'.C20>, <Cell '시트1수정'.C21>, <Cell '시트1수정'.C22>, <Cell '시트1수정'.C23>, <Cell '시트1수정'.C24>, <Cell '시트1수정'.C25>, <Cell '시트1수정'.C26>, <Cell '시트1수정'.C27>, <Cell '시트1수정'.C28>, <Cell '시트1수정'.C29>, <Cell '시트1수정'.C30>, <Cell '시트1수정'.C31>, <Cell '시트1수정'.C32>, <Cell '시트1수정'.C33>, <Cell '시트1수정'.C34>, <Cell '시트1수정'.C35>, <Cell '시트1수정'.C36>, <Cell '시트1수정'.C37>, <Cell '시트1수정'.C38>, <Cell '시트1수정'.C39>, <Cell '시트1수정'.C40>, <Cell '시트1수정'.C41>,

In [207]:
#파일열기

import openpyxl

#통합문서 객체명=파일여는 메소드
wb=openpyxl.load_workbook("./day03/test.xlsx")
print(wb.sheetnames) #시트를 열어주었기때문에 시트 이름 확인

ws=wb["new sheet02"]

['new sheet02', '시트1수정', 'new01', 'new sheet03', 'new sheet01']


In [83]:
# csv.DictWriter

cate = ["히어로명", "이름", "직업"]

data = [{"히어로명" : "스파이더맨", "이름":"피터 파커", "직업":"고등학생"},
       {"히어로명" : "아이언맨", "이름" : "토니 스타크", "직업" : "발명가"},
       {"히어로명" : "캡틴 아메리카", "이름" : "스티븐 로저스", "직업" :"군인"}]

with open("./day03/marvel.csv", "w", newline="") as f :
    # 쓰기 객체 생성
    w = csv.DictWriter(f, fieldnames = cate)
    # fieldnames : 열제목 설정
    w.writeheader() # 첫번째 행에 항목이름을 넣을 것인지 설정
    w.writerows(data)

print("marvel.csv파일 작성 완료")

marvel.csv파일 작성 완료


In [89]:
#넘파이 배열 생성
import numpy as np  #모듈이기때문에 넘파이를 사용하려면 import를 사용

#배열 생성
#배열명 =np.array(리스트나 튜플로 인수값으로 전달)

#1차원 배열 생성
li=[1,2,3,4] #리스트를 먼저 생성하고
arr=np.array(li) #배열명=np.array(리스트 인수 전달)
print(arr,type(arr)) #배열이기때문에 콤마 사라지고 타입도 class 'numpy.ndarray'라고 나옴
#배열array는 ndarray 클래스의 객체이기때문

tu=(1,2,3,4,5)
arr1=np.array(tu)
print(arr1,type(arr1)) #튜플도 인수 전달 가능

[1 2 3 4] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [107]:
#넘파이 2차원 리스트 배열 생성

li2=[[1,2,3],[4,5,6]]  #1행, 2행
arr2=np.array(li2) #2차원 배열 생성
print(arr2) #2차원 배열  2열 3행의 넘파이 구조가 생성

print()

tu1=((1,2,3,4),(1,2,3,4)) #튜플2개로 2차원의 배열구조 생성
arr3=np.array(tu1)
print(arr3) #2행 4열의 넘파이 구조 생성

print()

li3=[['안녕','헬로','하이'],['잘가','바이','씨유레이터']]
arr4=np.array(li3)
print(arr4) #문자열도 가능

print()

print(np.__version__) #사용중인 버전 확인

[[1 2 3]
 [4 5 6]]

[[1 2 3 4]
 [1 2 3 4]]

[['안녕' '헬로' '하이']
 ['잘가' '바이' '씨유레이터']]

1.26.4
