In [45]:
#배열의 요소 삭제
#np.delete(배열, 인덱스 번호, 축 설정)를 사용
#삭제하려는 행이 많을때는 인덱스 번호들을 리스트 형태로 묶어서 전달

import numpy as np

arr1= np.array([[1,2,3],[11,22,33],[111,222,333]])
print(arr1, arr1.dtype, arr1. shape, arr1.ndim) #3행 3열의 2차원 배열
print()

#1)배열의 행 삭제(axis = 0)
print(np.delete(arr1,1,axis=0))
print(np.delete(arr1,0,axis=0))
print()

#2)배열의 열 삭제(axis=1)
print(np.delete(arr1,0,axis=1)) #변수에 따로 넣어서 저장하지 않았기때문에 그냥 원본arr1에서 다시 실행되는것
print(np.delete(arr1,2,axis=1))
print()

#3)특정값만 삭제하기 => axis 축설정 하지 않는다!
print(np.delete(arr1, 1))
#이렇게 특정값만 삭제할 경우 축을 설정하지 않고 인덱스 번호를 적게되면
#arr1
#1행  1   2   3
#idx  0   1   2
#2행  11  22  33
#idx  3   4   5
#...
#인덱스 번호가 이렇게 쭉 하나로 이어져있도록 설계가 되기때문에 해당 번호에맞는 값이 삭제됨
print(np.delete(arr1,[3,8])) #여라깂을 전달해줄때는 리스트나 튜플의 형태로 전달해주어야함
print(np.delete(arr1,(3,8)))
print()

#)인덱스를 지정하여 여러개의 행, 여러개의 열 삭제하기
#여러개의 행 삭제
print(np.delete(arr1, [0,2],axis=0)) #여러개의 인덱스번호를 리스트 형태로 전달
print(np.delete(arr1,[1,2],axis=0))
print()

#여러개의 열삭제
print(np.delete(arr1,[0,1],axis=1))
print(np.delete(arr1,[0,2],axis=1))
print(np.delete(arr1,[1,2],axis=1))
print()

#슬라이싱을 이용하여 향과 열 삭제하기
# print(np.delete(arr1,[:2],axis=0)) 배열삭제에 인덱스를 사용한다면 그냥 np.delete를 사용하면 에러가 남
print(np.delete(arr1,np.s_[0:2],axis=0))
#슬라이싱을 사용하려면 슬라이싱 인덱스 번호앞에 np.s_를 붙여야하고
#슬라이싱은 끝값번호보다 하나 덜 가져오기때문에 1~2행 두개를 삭제해달라고 하는것!

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]] int32 (3, 3) 2

[[  1   2   3]
 [111 222 333]]
[[ 11  22  33]
 [111 222 333]]

[[  2   3]
 [ 22  33]
 [222 333]]
[[  1   2]
 [ 11  22]
 [111 222]]

[  1   3  11  22  33 111 222 333]
[  1   2   3  22  33 111 222]
[  1   2   3  22  33 111 222]

[[11 22 33]]
[[1 2 3]]

[[  3]
 [ 33]
 [333]]
[[  2]
 [ 22]
 [222]]
[[  1]
 [ 11]
 [111]]

[[111 222 333]]


In [89]:
#배열의 사칙연산

#2행 2열을 가진 2개의 배열생성
ar1=np.array([[10,20],[20,20]])
print(ar1,ar1.shape,ar1.ndim,ar1.dtype) #2행 2열

ar2=np.array([[50,60],[70,80]])
print(ar2,ar2.shape,ar2.ndim,ar2.dtype)
print()

print(f"ar1+ar2=\n{ar1+ar2}")
print()
#이렇게 행렬이 같은 경우는 행렬이 같은 배열의 연산은 같은 위치의 요소끼리 연산


#크기가 서로 다른 배열끼리의 사칙연산 : 브로드캐스팅
#브로드 캐스팅: 크기가 서로 다른 배열끼리의 사칙연산을 가능하게함

ar1=np.array([1,2,3])
print(ar1,ar1.shape,ar1.ndim) #1행 3열 1차원 배열

ar2=np.array([5])
print(ar2,ar2.shape,ar2.ndim) #1행1열 1차원

ar3=np.array([[1,2,3],[4,5,6]])
print(ar3,ar3.shape, ar3.ndim) #2행 3열의 2차원

ar4=np.array([[1,2],[3,4]])
print(ar4,ar4.shape,ar2.ndim)#2행 2열의 2차원
print()

#1)행의 갯수가 다르고 열의갯수가 같은경우 (계산가능함! 단 차원은 달라야함)
print(ar1+ar3) #1차원+2차원
#결과 2행3열로 나옴 #둘중에 더 작은 차원에서 큰 차원을 더하는 형식
print()

#2)행의 갯수가 같고 열의 갯수가 다른경우(계산가능함! 단 1차원에서만 가능)
print(ar1+ar2)

#3)행의 갯수가 같고 열의 갯수가 다른 2차원 배열의 경우
# print(ar3+ar4) #계산 불가능 #ValueError발생

#4)1차원과 2차원이 있을떄(1차원의 값이 1개이거나 or 열의갯수가 같은 경우에만 계산 가능)
print(ar1+ar3)
print(ar2+ar3)
print(ar2+ar4)

[[10 20]
 [20 20]] (2, 2) 2 int32
[[50 60]
 [70 80]] (2, 2) 2 int32

ar1+ar2=
[[ 60  80]
 [ 90 100]]

[1 2 3] (3,) 1
[5] (1,) 1
[[1 2 3]
 [4 5 6]] (2, 3) 2
[[1 2]
 [3 4]] (2, 2) 1

[[2 4 6]
 [5 7 9]]

[6 7 8]
[[2 4 6]
 [5 7 9]]
[[ 6  7  8]
 [ 9 10 11]]
[[6 7]
 [8 9]]


In [111]:
#배열의 산술연산 함수

#+ : np.add
#- : np.subtract
# * : np.multiply
# / : np.divide
# // : np.floor_divide
# % : np.mod  / np.remainder 
# ** : np.power

ar1=np.array([[1,3,5],[7,9,11]])
ar2=np.array([[2,5,7],[11,12,8]])

print(np.add(ar1,ar2))
print(np.subtract(ar1,ar2))
print(np.multiply(ar1,ar2))
print(np.divide(ar1,ar2))
print(np.floor_divide(ar1,ar2))
print(np.mod(ar1,ar2))
print(np.remainder(ar1,ar2))
print(np.power(ar1,ar2))

[[ 3  8 12]
 [18 21 19]]
[[-1 -2 -2]
 [-4 -3  3]]
[[  2  15  35]
 [ 77 108  88]]
[[0.5        0.6        0.71428571]
 [0.63636364 0.75       1.375     ]]
[[0 0 0]
 [0 0 1]]
[[1 3 5]
 [7 9 3]]
[[1 3 5]
 [7 9 3]]
[[          1         243       78125]
 [ 1977326743 -1038305055   214358881]]


In [3]:
#<실습>
#1~5까지 실수로 이루어진 배열 생성
import numpy as np

ar1=np.arange(1,6).astype("float")
print(ar1)

#1로만 이루어진 정수 10개를 요소로 가지는 2행 배열 생성

ar2=np.ones((2,5),dtype='i')
print(ar2)
print()
#위의 2개의 배열을 가지고 배열요소를 덧셈한 배열, 뺄셈한 배열 생성(배열2개 생성)
ar_add=np.add(ar1,ar2)
print(ar_add)
print()

ar_sub=np.subtract(ar1,ar2)
print(ar_sub)
print()
#3번에서 만든 배열2개를 하나의 배열로 합치는데 행기준으로 합치기
ar_add1=np.append(ar_add,ar_sub,axis=0)
print(ar_add1)
print()
#4번까지 만들어진 배열로 인덱스번호 2,4열 삭제 , 인덱스 번호 1,3행 삭제
print(np.delete(ar_add1,[2,4],axis=1))
print()
print(np.delete(ar_add1,[1,3],axis=0))

[1. 2. 3. 4. 5.]
[[1 1 1 1 1]
 [1 1 1 1 1]]

[[2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]]

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

[[2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

[[2. 3. 5.]
 [2. 3. 5.]
 [0. 1. 3.]
 [0. 1. 3.]]

[[2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4.]]


In [199]:
#배열 요소 재배치함수
#배열.transpose() : 배열 전치 함수

t=np.array([[1,2,3],[4,5,6]])
print(t,t.dtype, t.shape, t.ndim)
print()

#0행 1열의 값 / 1행 0열의 값 (번호: 인덱스 기준)
print(t[0][1]) #2
print(t[1][0]) #4
print()

#행과열 전치하기
t=t.transpose()
print(t)
print()

##0행 1열의 값 / 1행 0열의 값(번호: 인덱스 기준)
print(t[0][1]) #4
print(t[1][0]) #2
print()

#np.transpose()는 .T로 줄여서 사용가능
t=t.T
print(t) #다시 전치하기 전으로 돌아옴!

[[1 2 3]
 [4 5 6]] int32 (2, 3) 2

2
4

[[1 4]
 [2 5]
 [3 6]]

4
2

[[1 2 3]
 [4 5 6]]


In [219]:
import numpy as np
#배열.reshape(행,열) : 지정해준 행열대로 배열 재배치

ar1=np.arange(1,11)
print(ar1) #1행의 10열 1차원 배열
print()

print(ar1.reshape(2,5)) #2행의 5열로 배열 재배치 일어남
print()

#arange와 사용할 경우 reshape바로 붙여서 사용가능함
ar2=np.arange(3,21,3).reshape(2,3)
print(ar2)

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 3  6  9]
 [12 15 18]]


In [255]:
#배열의 기본 통계함수

#1차원 배열
ar1=np.arange(1,6)
print(ar1,ar1.shape,ar1.ndim) #1차원의 1행 5열 배열
print()

#배열.sum()
print(ar1.sum(),type(ar1.sum())) #배열요소 전체 더한값 / 값이1개만 있으니 스칼라의 형태로 출력
print(ar1[3:].sum()) #인덱스 번호 사용하여 3번부터 끝까지 더한값
print(ar1[::].sum())
print()

#배열.max()
print(ar1.max()) #배열의 요소중 가장 큰값 찾아줌
print()

#배열. min()
print(ar1.min()) #배열의 요소중 가장 작은값 찾아줌
print()

#배열. mean() : 평균
print(ar1.mean()) #배열의요소의 평균값 반환
#정수로 값을 넣어도 결과 실수로 출력 
#파이썬에서 나눗셈은 무조건 결과 실수 출력된다고했는데 평균을 계산 할때 나눗셈이 무조건 들어가기 때문에
#실수로 출력되는것. 만약이를 정수로 출력하고싶다면 정수로 형변환 해주어야함
print(ar1.mean().astype("int"))
print()
#이 경우 dtype으로 하면 에러가 나기때문에 평균반환한것을 정수로 만들고싶다면 무조건! 항상! astype사용해야함

#배열.cumsum() : 누적값
print(ar1.cumsum()) #누적 합계. 배열의 형태로 반환
#[1 2 3 4 5]
#1+2=3
#3+3=6
#6+4=10
#10+5=15

[1 2 3 4 5] (5,) 1

15 <class 'numpy.int32'>
9
15

5

1

3.0
3

[ 1  3  6 10 15]


In [309]:
#배열의 기본함수 2차원에서 사용하기
arr2=np.arange(1,21).reshape(4,5)
print(arr2,arr2.shape,arr2.ndim) #4행 5열의 2차원 배열
print()

#배열.sum()
print(arr2.sum()) #요소 전체의 값 전부 다 더해서210
print(arr2[2].sum()) #3번째 행 합 구하기
print(arr2[0:2].sum()) #1~2번째까지의 합
print()

#배열.max()
print(arr2.max()) #전체요소 중에서 가장 큰 값
print(arr2.max(axis=0)) #배열의 통계함수에서는 축 설정값이 반대. 즉 axis=0은 열 1이 행
#열중에서 큰값만 뽑은것
print(arr2.max(axis=1)) #행중에 큰값
print()

#배열.min
print(arr2.min(axis=1)) #행기준 최소값
print(arr2.min(axis=0)) #열기준 최소값
print()

#누적합계
print(arr2.cumsum()) #전체의 누적합
print(arr2.cumsum(axis=0)) #열기준 누적값
print(arr2.cumsum(axis=1)) #행기준 누적값
print()

#평균
print(arr2.mean()) #전체요소의 평균 반환
print()
print(arr2.mean(axis=0)) #열기준 평균
print(arr2.mean(axis=1)) #행기준 평균

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] (4, 5) 2

210
65
55

20
[16 17 18 19 20]
[ 5 10 15 20]

[ 1  6 11 16]
[1 2 3 4 5]

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
[[ 1  2  3  4  5]
 [ 7  9 11 13 15]
 [18 21 24 27 30]
 [34 38 42 46 50]]
[[ 1  3  6 10 15]
 [ 6 13 21 30 40]
 [11 23 36 50 65]
 [16 33 51 70 90]]

10.5

[ 8.5  9.5 10.5 11.5 12.5]
[ 3.  8. 13. 18.]


In [351]:
#<실습>
#1부터 20까지의 숫자 중 홀수로만 구성된 2행 5열의 배열 생성 후
ar1=np.arange(1,21,2).reshape(2,5)
print(ar1)

#행과 열기준의 각각의 평균, 합계출력
print(f"행기준 평균 : {ar1.mean(axis=1)}")
print(f"행기준 합계 : {ar1.sum(axis=1)}")

print(f"열기준 평균: {ar1.mean(axis=0)}")
print(f"열기준 합계: {ar1.sum(axis=0)}")

#2) 위에서 만든 배열의 각 행마다의 평균, 합계,최대값, 최소값 출력

for i,j in enumerate(ar1):
    print(f"{i+1}번째 행의 평균: {j.mean()}, 합계: {j.sum()}, 최대값: {j.max()}, 최소값: {j.min()}")
#배열도 리스트처럼 enumerate사용가능.
print()


#3)1번에서 만든 배열로 배열의 각 "열"마다의 평균,합계,최대값, 최소값 출력
ar1=ar1.T #전치해서 행과 열 바꿔줌

for i,j in enumerate(ar1):
    print(f"{i+1}번째 행의 평균: {j.mean()}, 합계: {j.sum()}, 최대값: {j.max()}, 최소값: {j.min()}")

#반복문에서 굳이 축설정안하는 이유.
#반복문을 사용했기때문에 인덱스번호와 각 행별로 출력됨. 어차피 반복문때문에 한행씩만 출력될것이기때문에 굳이 축 설정을 해줄 이유가 없음.
#게다가 j를 사용하지 않고 그냥 원본 배열사용 후 축설정을 해주었다면 각각 설정한 축마다의 값이 반복적으로 출력되기때문에 틀림!

[[ 1  3  5  7  9]
 [11 13 15 17 19]]
행기준 평균 : [ 5. 15.]
행기준 합계 : [25 75]
열기준 평균: [ 6.  8. 10. 12. 14.]
열기준 합계: [12 16 20 24 28]
1번째 행의 평균: 5.0, 합계: 25, 최대값: 9, 최소값: 1
2번째 행의 평균: 15.0, 합계: 75, 최대값: 19, 최소값: 11

1번째 행의 평균: 6.0, 합계: 12, 최대값: 11, 최소값: 1
2번째 행의 평균: 8.0, 합계: 16, 최대값: 13, 최소값: 3
3번째 행의 평균: 10.0, 합계: 20, 최대값: 15, 최소값: 5
4번째 행의 평균: 12.0, 합계: 24, 최대값: 17, 최소값: 7
5번째 행의 평균: 14.0, 합계: 28, 최대값: 19, 최소값: 9
