In [51]:
#넘파이 배열의 요소 접근

import numpy as np

arr1=np.array([1,2,3,4,5,6])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr1,type(arr1)) #1행의 6열 1차원 배열
print(arr2,type(arr2)) #3행 3열의 2차원 배열

print()

#1차원 배열의 요소 접근
print(arr1[2],type(arr1[2])) #배열명[인덱스 번호]
#넘파이에서 배열(array)의 인덱스 해도 리스트와 동일하게 개별 데이터 자료형으로 출력
print(arr1[1:3],type(arr1[1:3])) #리스트와 동일하게 슬라이싱하면 배열(array)자료형으로 출력
print(arr1[::2]) #2씩 건너뛰는 것도 가능!
print()

#2차원 배열의 요소 접근
print(arr2[0],type(arr2[0])) #2차원 배열안에 있는 첫번쨰 행 가지고 온것
print(arr2[1][2],type(arr2[1][2])) #인덱싱이므로 개별타입 그대로 INT출력
#2행 3열에 요소에 접근
print(arr2[:2]) #1,2행만 가져옴. 슬라이싱하면 하나 덜 가지고 오기 때문
print(arr2[:2][1]) #슬라이싱 행 중 1번 인덱스만 가지고옴
print(arr2[:2][1][2])
print(arr2[0][2])

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>

3 <class 'numpy.int32'>
[2 3] <class 'numpy.ndarray'>
[1 3 5]

[1 2 3] <class 'numpy.ndarray'>
6 <class 'numpy.int32'>
[[1 2 3]
 [4 5 6]]
[4 5 6]
6
3


In [59]:
#넘파이 배열 요소 접근
import numpy as np

#1차원 배열만들기
arr1=np.array([1,2]) #1차원의 1열 2행
print(arr1,type(arr1))

arr2=np.array([[1,2,3.0],[4,5,6]])
print(arr2,type(arr2)) #배열은 요소를 하나만 가질 수 있기때문에 실수형이 하나라도 있다면
#전부다 실수로 변함

[1 2] <class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'>


In [105]:
#넘파이 객체의 속성 / 메소드

#.dtype : 배열의 타입을 알려줌
print(arr1.dtype) #정수형 int32 배열임을 알려줌 

arr3=np.array([1,2,3,4.0]) #이것도 실수하나 있어서 전부 실수로 변함
print(arr3.dtype) #float64 실수형 배열
print(arr2.dtype) #아까 만든 실수형 배열
print()

#.shape : 차원의 크기(행,열)를 튜플로 알려줌
print(arr1.shape) #1차원의 데이터는 (열,)이런 형태로 되어있음. 그래서 (2,)
print(arr2.shape)
print(arr2) #(행,열)의 형태로 반환 2행의 3열
print(arr3.shape)
print(arr3) #1차원의 데이터는 행이 하나만 있으니까 열의 갯수를 앞에 반환.
print()

#.ndim: 차원의 수 반환
print(arr1.ndim) #1차원이기때문에 숫자 1반환
print(arr2.ndim)
print(arr3.ndim)
print()

#.size : 배열의 요소갯수 반환 / len()는 값이 다르게 나오기때문에 .size로 배열의 요소 파악해야함!
print(arr1.size)
print(arr2.size)
print(arr3.size)

int32
float64
float64

(2,)
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]
(4,)
[1. 2. 3. 4.]

1
2
1

2
6
4


In [5]:
#스칼라 : 정수나 실수 하나의 물리량을 가진 값
#넘파이 모듈은 선형대수를 기반으로 만들기떄문에 스칼라는 숫자로만 사용

import numpy as np

scalar=np.array(10) #스칼라라는 변수에 배열로 값을 1개만 넣음
print(scalar,type(scalar)) #물리량하나. 배열의 형태가 아닌것(행렬이 아님)
print(scalar, scalar.dtype, scalar.ndim, scalar.shape, scalar.size)
#스칼라는 배열이 아니기때문에 차원이 0개이고
#형상(shape)dms 빈튜플

#스칼라는 값이 1개이기때문에 숫자처럼 사용이 가능함
print(scalar==0)
print(scalar+10)

10 <class 'numpy.ndarray'>
10 int32 0 () 1
False
20


In [1]:
#벡터 : 크기와 방향을 가진 물리량(크기만 가진 물리량은 스칼라)

import numpy as np

ar1=np.array([1,2,3])
print(ar1, ar1.ndim, ar1.dtype,ar1.shape,ar1.size)
#1차원이기때문에 형상은 1차원으로 출력
#크기가 (3,)인 1차원 배열을 표현. 한방향  → 으로 나아가고있음 (행벡터)

ar2=np.array([[1,2,3]])
print(ar2,ar2.ndim,ar2.dtype,ar2.shape,ar2.size)
#2차원 배열에 크기가 (1행3열) 한방향  → 으로 나아가고있음 (행벡터)

ar3=np.array([[1],[2],[3]])
print(ar3, ar3.ndim, ar3.dtype,ar3.shape,ar3.size)
#2차원 배열의 3행의 1열 열방향 ↓과 행뱡향 → 으로 나아가고있기때문에 벡터가 아니라 매트릭스
#값이 1개더라도 1행이라는 크기와 방향을 가지기 때문에 일정 방향으로 가고있다고 봐야함
#두방향으로 나아간다면 벡터가 아니라 매트릭스

ar4=np.array([[1,2],[2,4]])
print(ar4, ar4.ndim,ar4.dtype,ar4.shape,ar4.size)
#2차원이고 열방향, 행방향 모두로 뻗어나가고있기때문에 벡터가 아니라 매트릭스
#2행의 2열 2차원의 배열
#벡터는 무조건 한방향이어야함. 열방향일거면 열방향으로, 행방향이면 행방향으로!

[1 2 3] 1 int32 (3,) 3
[[1 2 3]] 2 int32 (1, 3) 3
[[1]
 [2]
 [3]] 2 int32 (3, 1) 3
[[1 2]
 [2 4]] 2 int32 (2, 2) 4


In [21]:
#벡터의 크기 : norm

#사용자 정의함수를 통해 벡터의 크기인 norm구하기
def pytagoras(a,b):
    c=(a**2+b**2)**0.5
    print(f"높이{a}, 밑변{b}, 빗변의 길이{c}")

pytagoras(3,4)

#np.linalg(선형대수학을 모아놓은 함수)
print(np.linalg.norm([3,4])) #노름의 크기를 구함

#<노름 크기 구하기 실습>
print(np.linalg.norm([10,13]))

높이3, 밑변4, 빗변의 길이5.0
5.0
16.401219466856727


In [29]:
#매트릭스
#행과열을 가진 데이터 구조
#매트릭스의 경우 인덱스 번호 0번부터 시작
#벡터를 행이나 열방향으로 쌓아서 만듬

import numpy as np

matrix=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(matrix,type(matrix)) #3헹 3열
print(matrix, matrix.dtype,matrix.ndim,matrix.shape, matrix.size)

[[1 2 3]
 [2 3 4]
 [3 4 5]] <class 'numpy.ndarray'>
[[1 2 3]
 [2 3 4]
 [3 4 5]] int32 2 (3, 3) 9


In [49]:
#행렬의 랭크
#선형종속: 다른 벡터의 조합으로 만들 수 있는 벡터
#선형독립: 다른 벡터의 조합으로 만들 수 없는 벡터
#행렬의 랭크 : 전체 벡터의 수 - 선형종속 수

ma1=np.array([[1,2,4],[2,4,8]])
print(ma1, ma1.shape)
print(f"ma1의 행렬의 랭크: {np.linalg.matrix_rank(ma1)}")
#첫번째 행인 [1,2,3]*2를 하면 두번째 행인 [2,4,5]가 되므로
#첫번쨰 행이 선형독립, 두번째 행이 선형종속
#그러면 전체 행(2)-선형종속(1)=1

ma2=np.array([[1,2,4],[2,4,8],[3,4,5]])
print(ma2,ma2.shape) #3행 3열의 벡터
print(f"ma2의 행렬의 랭크:{np.linalg.matrix_rank(ma2)}")

ma3=np.array([[1,2,3],[2,5,7],[3,4,7]])
print(ma3, ma3.shape)
print(f"ma3의 행렬의 랭크: {np.linalg.matrix_rank(ma3)}")
#열기준으로 보면 1,2행을 더하면 3행이 나오기때문에 1,2행이 선형독립이고 
#조합으로 나올 수 있는 3행이 선형종속
#ma3은 열기준으로 쌓아놓은 벡터. 열기준으로 벡터가 계산되기때문에..!

[[1 2 4]
 [2 4 8]] (2, 3)
ma1의 행렬의 랭크: 1
[[1 2 4]
 [2 4 8]
 [3 4 5]] (3, 3)
ma2의 행렬의 랭크:2
[[1 2 3]
 [2 5 7]
 [3 4 7]] (3, 3)
ma3의 행렬의 랭크: 2


In [67]:
#넘파이 배열의 데이터 타입

#숫자형_정수형
li1=[1,3,5,7,9]
arr=np.array(li1)
print(arr,arr.dtype) #int32 정수형 배열의 데이터 타입
print()

#숫자형_실수형
li2=[1.2,3.4,5.6]
arr1=np.array(li2)
print(arr1,arr1.dtype) #float64 실수형

#숫자형_복소수형
li3=[(1+1j)+(2+3j)]
arr2=np.array(li3)
print(arr2,arr2.dtype) #complex128 복소수형

#문자형
li4=["안녕","하세요"]
arr3=np.array(li4)
print(arr3, arr3.dtype) #<U3 문자형

#논리형
li5=[True, True, False, False]
arr4=np.array(li5)
print(arr4,arr4.dtype) #bool 논리형

#type옆에 있는 숫자는 값을 메모리에 저장하는 필요한 비트(bit)수

[1 3 5 7 9] int32

[1.2 3.4 5.6] float64
[3.+4.j] complex128
['안녕' '하세요'] <U3
[ True  True False False] bool


In [85]:
#데이터 타입별 합쳐지는 데이터 타입

li1=[1,2,True,False]
ar1=np.array(li1)
print(ar1,ar1.dtype) #정수 + 논리 = 정수

li2=[1,2,3.14]
ar2=np.array(li2)
print(ar2,ar2.dtype) #정수+실수 = 실수

li3=["10",11,23]
ar3=np.array(li3)
print(ar3,ar3.dtype) #숫자+문자 = 문자 (숫자에 따옴표 붙여져서 출력)

li4=[True,"True",False]
ar4=np.array(li4)
print(ar4,ar4.dtype) #문자+논리 = 문자형(논리형에 따옴표 붙여져서 출력)


[1 2 1 0] int32
[1.   2.   3.14] float64
['10' '11' '23'] <U11
['True' 'True' 'False'] <U5


In [103]:
#dtype을 사용하여 원하는 데이터 정수형 만들기
#정수형 'i' =>int
li=[1,3.14,True,0.0]
print(li)

ar1=np.array(li,dtype="i")
print(ar1,ar1.dtype)
#dtype사용안하면 실수가 있기때문에 전부 실수로 변하지만
#dtype으로 지정하면 전부 정수타입으로 숫자가 변함 

#실수형 'f'=> float
ar2=np.array(li,dtype="f")
print(ar2,ar2.dtype)

#문자형'U'=>unicode
ar3=np.array(li,dtype='U')
print(ar3,ar3.dtype)

#논리형'?'
ar4=np.array(li,dtype="?")
print(ar4,ar4.dtype)

[1, 3.14, True, 0.0]
[1 3 1 0] int32
[1.   3.14 1.   0.  ] float32
['1' '3.14' 'True' '0.0'] <U4
[ True  True  True False] bool


In [183]:
#배열의 기본함수
#np.arange : 연속적인 정수, 실수 둘다 가능!
#np.astype : 원하는 데이터 타입으로 변경가능
#np.zeros : 0으로만 이뤄진 배열 만들기
#np.ones :  1로만 이뤄진 배열 만들기

#np.array(시작, 종료, 스텝)
print(list(range(1,10,2)))
arr=np.arange(1,10,2)
print(arr,type(arr)) #레인지를 사용한 연속적인 정수 벡터 생성
arr1=np.arange(0.1,2,0.2)
print(arr1)#실수 가능

arr=np.arange(1,10,2,dtype='f')
print(arr)#dtype이용해서 바꾸기 가능
print()

#np.astype
a1=np.array([1,2,3])
print(a1,a1.dtype) #정수형 배열

ar2=a1.astype(float)
print(ar2)

ar2=ar1.astype(bool)
print(ar2)

ar2=ar1.astype(str)
print(ar2)
print()

#np.zeros
ar2=np.zeros((4,5))
print(ar2,ar2.dtype, ar2.shape, ar2.ndim, ar2.size)
ar3=np.zeros((3,3))
print(ar3)
ar4=np.zeros((4,5),dtype="i") #타입을 지정하면 지정한 타입대로 나옴
print(ar4)
print()

#np.ones()
ar5=np.ones((3,3))
print(ar5) #타입지정안했기때문에 실수로 출력

ar5=np.ones((3,),dtype='i')
print(ar5,ar5.dtype, ar5.ndim, ar5.shape,ar5.size) #1행 

[1, 3, 5, 7, 9]
[1 3 5 7 9] <class 'numpy.ndarray'>
[0.1 0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7 1.9]
[1. 3. 5. 7. 9.]

[1 2 3] int32
[1. 2. 3.]
[ True  True  True False]
['1' '3' '1' '0']

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] float64 (4, 5) 2 20
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 1 1] int32 1 (3,) 3


In [213]:
# 배열의 요소 추가

#리스트 추가
li1=[1,2]
print(li1)
li1.append(3)
print(li1)
print()

#넘파이 추가
ar=np.array([[1],[3]])
print(ar,ar.ndim,ar.shape) #2차원 2행 1열
print()

#행추가(변수에 재할당을 해야함!!! 배열은 크기가 정해져있기때문에)
ar=np.append(ar,[[0]],axis=0)
print(ar,ar.shape) #3행 1열
print() #열이 없기때문에 열추가가 안됨

#열추가
ar=np.array([[0,0],[1,1],[2,2]])
print(ar,ar.shape) #3행 2열

ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])
result=np.append(ar1,ar2,axis=1)
print(result,result.shape, result.ndim)
ar3=np.array([[9,10,],[11,12]])
result=np.append(result,ar3,axis=1)
print(result)
print()

#배열의 요소 수정
#배열의 요소 수정방법은 리스트 요소 수정과 매우 비슷
ar1=np.array([1.0,2.2,100])
print(ar1,ar1.dtype) #실수가 포함되어있기때문에 실수형으로 출력

ar1[1]=50
print(ar1,ar1.dtype) #인덱스 번호 기준 1자리에 있었던 2.2가 50으로 변경. 
#값만 50이라는 값으로 수정되고 하나의 자료형만 있어야하기때문에 50은 그대로 들어가되, 실수가 됨

ar2=np.array([[1,2,3],[4,5,6]])
print(ar2,ar2.dtype) #정수형의 2행 3열 2차원 배열
ar2[1][0]=5
print(ar2)
ar2[0][0]=20
print(ar2)
ar2[1]=10
print(ar2)

[1, 2]
[1, 2, 3]

[[1]
 [3]] 2 (2, 1)

[[1]
 [3]
 [0]] (3, 1)

[[0 0]
 [1 1]
 [2 2]] (3, 2)
[[1 2 5 6]
 [3 4 7 8]] (2, 4) 2
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

[  1.    2.2 100. ] float64
[  1.  50. 100.] float64
[[1 2 3]
 [4 5 6]] int32
[[1 2 3]
 [5 5 6]]
[[20  2  3]
 [ 5  5  6]]
[[20  2  3]
 [10 10 10]]
